In [2]:
import numpy as np

## Write a Numpy program to compute the multiplication of two given matrixes

In [35]:
a = np.arange(0,6).reshape(2,3)

b = np.arange(0,15).reshape(3,5)

In [36]:
np.dot(a , b) 

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

## Write a NumPy program to compute the determinant of a given square array

In [46]:
c= np.array( [[ 25,  28,  31],[ 70,  82,  94],[ 216, 516, 123]])

In [47]:
np.linalg.det(c)

-62370.00000000005

## Write a NumPy program to compute the cross product of two given vectors

In [57]:
d = np.array( [21,51,65])

e = np.array( [16,51,56])

In [58]:
np.cross(d, e)

array([-459, -136,  255])

## Write a NumPy program to compute the condition number of a given matrix

In [55]:
f = np.array([[166,1,16],[65,15,615],[65,156,6]])

In [56]:
np.linalg.cond(f)

4.756431809916661

## Write a NumPy program to compute the inverse of a given matrix

In [59]:
g = np.array([[166,1,16],[65,15,615],[65,156,6]])

In [62]:
np.linalg.inv(g)

array([[ 6.09543796e-03, -1.58347841e-04, -2.38475664e-05],
       [-2.51734910e-03,  2.79811445e-06,  6.42612421e-03],
       [-5.82834522e-04,  1.64268396e-03, -1.54214262e-04]])